NYPL-Simplified/circulation-patron-web

.travis.yml, package.json, src/components/CatalogHandler.tsx, src/components/ContextProvider.tsx, src/components/Header.tsx, src/components/__tests__/CatalogHandler-test.tsx, src/components/__tests__/ContextProvider-test.tsx, src/components/__tests__/Header-test.tsx, src/index.tsx, src/routes.ts, src/server/index.tsx, src/testHelper.ts, typings.json, webpack.config.js
Added a small express-based node server that pre-fetches data for any route, renders the front-end as HTML, and provides the application state to the front-end JS.
=> node server with universal rendering

package.json, src/components/BookDetails.tsx, src/components/__tests__/BookDetails-test.tsx
Not sure if this is where we'll ultimately want it it but it was easy to put it here.
=> Added distributor to BookDetails fields. (Fixes #20).

package.json, src/components/BookDetails.tsx, src/components/ConfirmationPopup.tsx, src/components/RevokeButton.tsx, src/components/__tests__/BookDetails-test.tsx, src/components/__tests__/ConfirmationPopup-test.tsx, src/components/__tests__/RevokeButton-test.tsx
=> Added revoke button for open-access books.

config/dev.nypl.json, config/local.nypl.json, config/local.openebooks.json, config/prod.nypl.json, config/prod.openebooks.json, config/qa.nypl.json, config/qa.openebooks.json, src/components/CatalogHandler.tsx, src/components/__tests__/CatalogHandler-test.tsx, src/server/index.tsx
Redirect to /collection/groups instead of displaying books at root url, to avoid #38.
=> Redirect from / to /collection/groups

package.json, src/server/index.tsx
This includes a minor change to update the version of node-sass to work with node:8.x and a code condition to allow for comments (with #) in the configuration of the library config list file. In passing, do we need to check for blank lines and skip them as well?
=> Test update sass

src/interfaces.ts, src/server/LibraryDataCache.ts, src/server/__tests__/LibraryDataCache-test.ts, src/server/index.tsx
Pulls in the CSS hrefs from the authentication document and adds them to the HTML header
=> Library Data CSS

CHANGELOG.md, package-lock.json, package.json, src/components/Header.tsx, src/components/ReportProblemForm.tsx, src/server/LibraryDataCache.ts, tslint.json
Resolves [SIMPLY-2135](https://jira.nypl.org/browse/SIMPLY-2135).
I set the `option`s to take in `aria-selected={false}` because those values were not updating when a new value was selected (the form's select value isn't stored and only used when submitting). I think it's fine for now and we can review it again when bigger updates are being made.
=> Adding tslint-react-a11y.

CHANGELOG.md, package-lock.json, package.json
I also updated the changelog but didn't bump the version number because I know this version hasn't been released (merged to master) yet.
=> Update opds-web-client dep

package-lock.json, package.json, src/utils/reader.ts
- add link to navigate back to previous page
- if there is no link to previous page then navigate to host (is there a better fallback in this case? In particular I am concerned if someone does directly to the reader via URL (as opposed to from within the app) in the multi-library context and hits the back arrow)
- I tried passing the router variables from WebpubViewer -> Reader but they seemed to be getting overridden.
=> add link to previous page

package-lock.json, package.json
This PR just bumps the version of opds-web-client. I don't include a version or changelog change. Let me know if you think it warrants that @EdwinGuzman
=> bump opds-web-client

CHANGELOG.md, src/auth/AuthButton.tsx, src/auth/BasicAuthButton.tsx, src/auth/BasicAuthForm.tsx, src/auth/SamlAuthForm.tsx, src/auth/basicAuthPlugin.tsx, src/auth/cleverAuthButton.tsx, src/auth/samlAuthPlugin.tsx, src/components/Auth.tsx, src/components/Modal.tsx, src/components/__tests__/Auth.test.tsx, src/test-utils/fixtures/auth.ts
- Display login logos instead of combo box when there are fewer than 5 AuthProviders
- When there are 2-4 AuthProviders show Auth buttons instead
=> Display login logos instead of combo box when there are 2-4 AuthProviders

.github/workflows/ci.yml
- Update GitHub Actions CI to provide ability for the axis-now submodule to be installed during the CI checks.
=> TESTING Adding support to GitHub Actions for Submodule

.github/workflows/publish-beta.yml
Changes to Docker Build V2 
This can't be tested until we merge it, sadly.
=> Using docker build action v2

CHANGELOG.md, src/hooks/useAuth.ts
- Locally stored books are removed when a user logs out
=> Remove locally stored book resources when user logs out

.github/workflows/ci.yml, CHANGELOG.md
This adds an action to enforce that we update the changelog unless we add a no-changelog label
=> Check changelog

.github/workflows/publish-qa.yml, .github/workflows/release-prod.yml, CHANGELOG.md, package-lock.json, package.json
This fixes workflows and moves us to v3.1.1
=> Fix workflows

.github/workflows/publish-qa.yml, .github/workflows/release-prod.yml
This pulls the workflow syntax hotfix back from production into qa
=> Pull hotfix back from production

CHANGELOG.md, src/auth/BasicAuthHandler.tsx, src/auth/__tests__/BasicAuthForm.test.tsx
Adds ability to choose another login method once you've landed on the basic auth form. Only does so if library has multiple methods
=> Choose another login

CHANGELOG.md, package.json, src/components/BookCover.tsx, src/components/Lane.tsx, src/components/LazyImage.tsx, src/components/LazyLoadImage.tsx, src/components/__tests__/LazyImage.test.tsx
https://jira.nypl.org/browse/SIMPLY-3311
Hi, team. I took an initial crack at this.  Let me know if this is kind of what you had in mind.  Thx!
=> Simply 3311 image optimization new

CHANGELOG.md, src/components/Button/styles.ts, src/components/Header.tsx, src/components/MyBooks.tsx, src/components/OpenEbooksLanding.tsx, src/components/SignOut.tsx, src/components/__tests__/SignOut.test.tsx, src/components/__tests__/__snapshots__/Button.test.tsx.snap
https://jira.nypl.org/browse/SIMPLY-3318
Figma:  https://www.figma.com/file/vcWnIIbpNtZE7M5n2lfegC/Open-E-Books?node-id=733%3A3296
**Note: See JIRA story comments for clarification about design.**
=> [SIMPLY-3318] Add catalog button on openE home page.

.github/workflows/integration.yml, CHANGELOG.md
This is a PR for [SIMPLY-3374](https://jira.nypl.org/browse/SIMPLY-3374) to add integration testing via a webhook to Lyrasis' integration test repo. No feedback will be presented to this repository and it should only be run on commits to release branches (dev, qa, production). Failures will have to be recognized on their end and brought to our attention
=> SIMPLY-3374 Lyrasis integration tests

CHANGELOG.md, src/dataflow/withAppProps.ts
https://jira.nypl.org/browse/SIMPLY-3535
=> [SIMPLY-35-35] Track better startup errors 

CHANGELOG.md, package-lock.json, src/components/BookList.tsx, src/components/__tests__/BookList.test.tsx, src/components/bookDetails/index.tsx, src/dataflow/opds1/__tests__/parse.test.ts, src/dataflow/opds1/parse.ts, src/utils/__tests__/book.test.ts, src/utils/book.tsx
This is a draft PR to resolve https://jira.nypl.org/browse/SIMPLY-3653 where contributors are not showing up right in list view or book details view.
=> contributors
