- src/components/BookDetails.tsx
If one of the categories is missing a label or scheme we should render the book without the category instead of throwing an exception.
> Made category code more robust in case of missing info in the OPDS feed.

- package.json
- src/components/CatalogHandler.tsx
- src/components/Footer.tsx
- src/components/__tests__/CatalogHandler-test.tsx
- src/components/__tests__/Footer-test.tsx
This fixes #22. 
I moved the code to handle the specific link types here from https://github.com/NYPL-Simplified/opds-web-client/pull/153.
> Added footer with about-type links.

- package.json
- typings.json
I'm hoping this will fix an issue with jenkins where the first build after a code update fails to find redux. We were already using the typings from dt in opds-web-client.
One weird thing is that redux has its own typings, but they don't seem to get picked up by the react-redux typings, so I also needed redux typings from dt.
> Updated redux and react-redux and switched to typings from dt.

- CHANGELOG.md
- LICENSE
- README.md
- package.json
Resolves [SIMPLY-2542](https://jira.nypl.org/browse/SIMPLY-2542)
Small PR to add more details on how to start the app. Mostly came up from asking @adriana-alter to review and try all combinations herself, and finding that some don't work (mostly missing that libraries should be registered in order for the app to work).
Also added a separate file for the license.
> Updating the README for documentation on app start up.

- .gitmodules
- .travis.yml
This branch adds a submodule for docker, so we can trigger builds in docker hub. It should be configured the same way as the ones for circulation.
> Docker submodule

- README.md
We don't have a build of the beta branch yet in docker hub because no commits have been made to the branch yet. This is mainly a bump to get that to build so we can deploy it at Lyrasis. However, it also makes the docker hub badge a link to docker hub :)
> Bump beta to get it to build

- .travis.yml
- CHANGELOG.md
- package-lock.json
- package.json
The travis CI workflow is redundant now that we have the github actions version, so this removes it.
> remove travis file

- CHANGELOG.md
- src/hooks/useBorrow.ts
This PR fixes a simple error we got in the borrow card where we would call `setLoading(false)` after the component had already mounted. We now track whether the component is mounted or not and only update the sate if it is still mounted (which would happen if there was an error in the borrow api call).
> Fix set state on unmounted component

- CHANGELOG.md
- README.md
- src/components/__tests__/Auth.test.tsx
- src/components/__tests__/BasicAuthForm.test.tsx
- src/components/__tests__/BookListItem.test.tsx
- src/components/__tests__/BreadcrumbBar.test.tsx
- src/components/__tests__/Button.test.tsx
- src/components/__tests__/Collection.test.tsx
- src/components/__tests__/Error.test.tsx
- src/components/__tests__/Lane.test.tsx
- src/components/__tests__/Layout.test.tsx
- src/components/__tests__/ListFilters.test.tsx
- src/components/__tests__/ListView.test.tsx
- src/components/__tests__/MyBooks.test.tsx
- src/components/__tests__/PageTitle.test.tsx
- src/components/__tests__/Search.test.tsx
- src/components/__tests__/TextInput.test.tsx
- src/components/__tests__/form.test.tsx
- src/components/bookDetails/__tests__/BookDetails.test.tsx
- src/components/bookDetails/__tests__/FulfillmentCard.test.tsx
- src/components/bookDetails/__tests__/Recommendations.test.tsx
This PR makes a simple language refactor across all of our test files and the readme. The result of `render` from `react-testing-library` is not actually a node. It is a set of utilities to query the dom by, as well as other utils we pass in via `test-utils/index.tsx`. I had started to transition slowly to using `utils` instead of `node`, but this should avoid confusion in the future.
> replace node with utils in tests

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/bookDetails/FulfillmentCard.tsx
- src/components/bookDetails/__tests__/FulfillmentCard.test.tsx
- src/utils/__tests__/book.test.ts
- src/utils/book.tsx
This PR removes download options for audiobooks since they cannot be played outside of SimplyE. Instead, we only show the "You are now ready to read this book in SimplyE!" banner.
> no audiobook downloads

- README.md
- next.config.js
- src/components/Footer.tsx
- src/components/__tests__/Footer.test.tsx
- src/utils/env.ts
Currently in circulation-patron-web the default branding logic sprinkles Simply-E references throughout the app. This branding should be controlled by an environment variable of the type companion-app = "simplye" | "openebooks".
Requirements (to be confirmed)
When environment variable is "simplye"
-   Footer (display references to download SimplyE)
When environment variable is "openebooks"
-    Footer (remove eferences to download SimplyE)
> Add env variable to toggle SimplyE branding in footer

- src/components/bookDetails/__tests__/BookDetails.test.tsx
- src/components/bookDetails/index.tsx
Currently in circulation-patron-web the default branding logic sprinkles Simply-E references throughout the app. This branding should now be controlled by an environment variable of the type companion-app = "simplye" | "openebooks"/
For now I am just not showing the SimplyE sidebar when the COMPANION_APP is set to openebooks
NEXT_PUBLIC_COMPANION_APP=simplye or omitted 
<hr><hr>
<hr><hr>
NEXT_PUBLIC_COMPANION_APP=openebooks
> toggle SimplyE sidebar depending on COMPANION_APP

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/BookCover.tsx
- src/components/BookList.tsx
- src/css-overrides.css
- src/pages/_app.tsx
This PR updates the BookCover component so that it shows the medium icon while the image is loading and keeps it there in the case of an error. When the book finishes loading we now fade it in to view.
> update image fallback

- CHANGELOG.md
- src/components/__tests__/Auth.test.tsx
- src/components/__tests__/Link.test.tsx
- src/components/__tests__/MyBooks.test.tsx
- src/hooks/useAuth.ts
- src/test-utils/fixtures/library.ts
- src/test-utils/fixtures/recommendationsState.ts
- src/test-utils/fixtures/server.ts
We previously did not fetch loans on page load when auth credentials were detected. This caused page to indicate that you had not borrowed a book yet when in fact you had (until you navigate to /loans and fetch that data). Now I fetch loan data on page load when auth credentials are detected.
Note that this can cause some funkiness when you switch between libraries without signing out of the first one. It's not something users will be doing often, and we will look to fix it when we refactor the data fetching logic.
> Fetch loans on page load when auth credentials detected

- CHANGELOG.md
- src/components/Auth.tsx
- src/components/__tests__/Auth.test.tsx
- src/components/__tests__/BookListItem.test.tsx
- src/components/bookDetails/__tests__/FulfillmentCard.test.tsx
- src/components/context/ContextProvider.tsx
- src/hooks/useAuth.ts
- src/hooks/useBorrow.ts
- src/hooks/useEffectDebugger.ts
- src/hooks/useSetCollectionAndBook.ts
This resolves a bug in CPW caused by the 30 minute cache of loans data instituted by the server. Previously, we refetched the loans data quite often (relying on the browser cache to avoid network requests). This meant that after borrowing a book, we would then fetch loans and get stale information. To rectify this, OWC is set up to modify the redux loans state with the return value of a borrow request. 
What I've done here is to mimic the mobile apps, and only fetch loans once when the app starts, and then we simply maintain our internal state from there on out. This means we can become out of sync with the server, but will become eventually consistent (after the 30 minute cache expires). 
This PR also updates the url we fetch for loans from a manually created one to the one present in …
> Fetch loans only on app startup

- src/components/bookDetails/FulfillmentCard.tsx
- src/components/bookDetails/__tests__/FulfillmentCard.test.tsx
Currently in circulation-patron-web the default branding logic sprinkles Simply-E references throughout the app. Now this branding is controlled by an environment variable of the type  companion-app = "simplye" | "openebooks".
Requirements
When the environment variable is set to "openebooks" the Fulfillment Card changes from “You’re ready to read this book in SimplyE” to “You’re ready to read this book in Open eBooks”
When env variable is NOT set to "openebooks" continue displaying SimplyE verbiage
> display different copy for fullfillment card in OpenEBooks context

- src/hooks/useAuth.ts
This is an attempt to resolve issue where "log in" button in the navigation seemed to be working when logging in for the first time but was not functional after logging out when attempting to log back in again.
1. Run circulation-patron-web locally with SIMPLIFIED_CATALOG_BASE=http://qa.circulation.openebooks.us/USOEI/groups/ SHORTEN_URLS=false npm run dev
2. Go to index page: http://localhost:3000/
3. Click on log in the navigation
4. Login Modal appears and Log in using First Book credentials
5. Log Out
6. Click Log in in navigation
Expected: Login modal appears and allow First Book or Clever credentials.
Actual: Nothing happens
Note: Currently if you attempt to check out a book on the book details page then you are prompted to login which supports First Book login. The nav login seems …
> update signIn to showAuth form when "Sign In" is clicked

- README.md
- package.json
This is a very simply PR not really worthy of a version or changelog. It simply adds a new npm script to run the app with https. The default `npm run dev` will run it over http, and `npm run dev:https` will run it over https with the `dev-server.js` script.
> Add npm run dev:https

- next.config.js
- src/utils/axe.ts
- There were some type issues with React-Axe in circulation-patron-web and it needed some tweaks to be functional again. 
- In terms of testing I confirmed that I am now able to see the aXe logs when running `yarn dev:axe`
> update React aXe configuration

- src/components/bookDetails/index.tsx
- src/pages/_document.tsx
> <html> element must have a lang attribute. 
This PR adds `_document.tsx` to set the HTML lang to `en` by default. 
On the book details the title is h1 but the summary is h3. This PR updates the summary to H2 with the same styles applied.
> moderate: Heading levels should only increase by one https://dequeuniversity.com/rules/axe/3.5/heading-order?application=axeAPI
> a11y: resolve lang and heading aXe related issues

- src/components/Button/styles.ts
- src/components/MyBooks.tsx
- src/components/__tests__/__snapshots__/Button.test.tsx.snap
- src/components/bookDetails/__tests__/__snapshots__/BookDetails.test.tsx.snap
- src/theme/theme.ts
- focus was barely visible in Firefox since it was using browser defaults instead of styling from circulation-patron-web
- updated to use the same focus style as the Reakit button example: https://reakit.io/docs/button/#main 
After (in Firefox)
- filled/img button <img width="1282" alt="Screen Shot 2020-08-25 at 12 24 38 PM" src="https://user-images.githubusercontent.com/6998954/91201043-f917eb80-e6cd-11ea-8583-43b2c4f4e31b.png">
- ghost button <img width="1281" alt="Screen Shot 2020-08-25 at 12 24 19 PM" src="https://user-images.githubusercontent.com/6998954/91201046-f9b08200-e6cd-11ea-86d4-92a738670771.png">
Before (in Firefox)
> a11y: add visible focus to filled and ghost buttons

- src/components/__tests__/BookListItem.test.tsx
- src/components/bookDetails/__tests__/FulfillmentCard.test.tsx
- src/hooks/useBorrow.ts
- When there is an error in loans, it has no concept of which loan has errored, leading to an error message on all borrow buttons.
- This PR updates it so that the error message is only returned when the error url matches the book url.
The error URL for a book: https://qa-circulation.openebooks.us/USOEI/works/BOOKID looks like: https://qa-circulation.openebooks.us/USOEI/works/BOOKID/borrow/4 
Before: 
After:
> Loan Error message should not be global

- src/components/WebpubViewer.tsx
- src/utils/reader.ts
Re-assigns decryptor location so that tsc doesn't throw an error when the decryptor submodule is not available.
> Fix decryptor tsc errors

- .github/workflows/publish-beta.yml
- src/components/WebpubViewer.tsx
- src/utils/reader.ts
the interaction of TS/Node/Webpack/Babel means that dynamic imports are tricky, and debugging in different environments is causing different errors.  I
The root cause of this is that importing "axis-now-access-control/decryptor" throws a tsc error when the repo doesn't have access to the submodule.  I've gone and suppressed that warning.  
Based on the convos in slack earlier today, we might eventually take this out completely, and I think this is yet another point in favor of doing that.
> Uses ts-ignore instead of dynamic imports

- package-lock.json
- package.json
- Upgrade webpub-viewer to 0.2.2 to pull in the latest updates to parsing e-books (https://github.com/NYPL-Simplified/webpub-viewer/pull/172)
> update webpub-viewer to 0.2.2 

- .eslintrc.js
This fixes the axisnow eslint setting so that submodule continues to be linted
> Fix eslint in axisnow

- src/hooks/useSetCollectionAndBook.ts
My previous work removing the URL shortener somehow didn't take in to account that on the homepage there is no collection url in the browser, so you have to use the catalog url as a fallback. This should fix : )
> Show us collections!!

- .env
- README.md
- community-config.yml
- next.config.js
- src/components/WebpubViewer.tsx
- src/components/__tests__/WebpubViewer.test.tsx
- src/components/bookDetails/__tests__/FulfillmentCard.test.tsx
- src/config/index.ts
- src/interfaces.ts
- src/test-utils/mockConfig.ts
- src/types/declarations/AxisNowDecryptor.d.ts
- src/utils/env.ts
- src/utils/fulfill.ts
- src/utils/reader.ts
- src/utils/stub-decryptor.ts
We need to move the variable that indicates access to the axisnow decryptor back to an environment variable, and also stub it for when it isn't accessible to avoid webpack errors on build
> Axisnow issue

- src/components/Error.tsx
This reverses something I did which I thought would be nice, but isn't nice at all. From the 404 page, when you click a link to a library home page, we now push that state into history instead of replacing it, so you can go back to choose another.
> Push state from 404

- src/components/FulfillmentButton.tsx
- src/components/Link.tsx
- src/components/ListFilters.tsx
- src/components/Search.tsx
- src/components/__tests__/ListFilters.test.tsx
- src/components/__tests__/Search.test.tsx
This PR fixes the performance problem we saw when switching between list filters. I'll try to explain the underlying problem...
- The app uses `getStaticProps` for every page to fetch the library data we need. This means that the first time a route is requested, `getStaticProps` is run server-side, and then the page is rendered using that data. For the time being, this only loads the information we need for the library, so basically just the layout (the logo, library name, colors, etc). The actual collection or book data is fetched client-side (for now).
- Once we run `getStaticProps` on the server, the HTML that generates is sent to the client, and then cached. So subsequent requests to that page will be immediately responded to with the HTML already generated and ready on the server. …
> List filters delay

- src/components/MyBooks.tsx
- src/components/__tests__/MyBooks.test.tsx
This simple fix corrects the way that the loans page would resort after a second when you click the page. If two books don't have availability defined, we sort by title, which makes the sort "stable", meaning that it will return the same output every time if it is given the same input.
> Stable loans sort

- install-deps.sh
This fixes some syntax issues we had when constructing a `.npmrc` file to install the AxisNow Decryptor package.
> Fix npmrc generation in docker build

- src/hooks/useCollection.ts
This fixes a logical bug I made in my if/else statement for the error handling in `useCollection` so that 401 errors now correctly are passed down.
> fix error handling

- CHANGELOG.md
- src/components/BookList.tsx
- src/components/WebpubViewer.tsx
- src/components/__tests__/Search.test.tsx
- src/components/bookDetails/FulfillmentCard.tsx
- src/components/bookDetails/__tests__/BookDetails.test.tsx
- src/components/bookDetails/__tests__/Recommendations.test.tsx
- src/components/stories/BookListItem/FulfillableBook/OnlyCompanionApp.stories.tsx
- src/components/stories/BookListItem/FulfillableBook/PrefersCompanionApp.stories.tsx
- src/components/stories/BookListItem/FulfillableBook/PrefersWebApp.stories.tsx
- src/components/stories/BookListItem/OnHoldBook.stories.tsx
- src/config/fetch-config.d.ts
- src/dataflow/download.ts
- src/interfaces.ts
- src/test-utils/fixtures/book.ts
- src/utils/fulfill.ts
- tsconfig.json
This is a typescript option that was disabled when we began pulling in code from opds-web-client. This PR re-enables it to bring runtime safety guarantees for the future.
> Re-enable strict type checking

- CHANGELOG.md
- package-lock.json
- package.json
This bumps the changelog and version so we can merge 4.2.0 from `dev` to `qa`
> 4.2.0 to dev

- CHANGELOG.md
- package-lock.json
- package.json
- src/auth/useLogin.ts
- src/auth/useLoginRedirect.tsx
- src/test-utils/mockNextRouter.tsx
This is an attempt to fix the invalid redirect uri we would sometimes send during clever auth. The issue was caused by the fact that sometimes we would redirect before the client finishes rendering, which means that Next.js's `asPath` would have a full url in it instead of just the _path_. I put in a couple guards for this case but have not been able to fully test it.
> Fix invalid redirect URI

- CHANGELOG.md
- src/components/Error.tsx
- src/components/__tests__/Error.test.tsx
Display a page loader instead of an error screen when a 401 is caught.
https://jira.nypl.org/browse/SIMPLY-3496
> [SIMPLY-3496] 401 page is flashed during login redirection in CPW

- CHANGELOG.md
- next.config.js
- src/auth/useCredentials.ts
- src/components/context/__tests__/UserContext.test.tsx
- src/pages/_error.tsx
- src/utils/constants.ts
There was an undefined error when logging in via clever sometimes. https://jira.nypl.org/browse/SIMPLY-3466 .
I'm not sure exactly what the underlying bug was, but it had to do with how we were removing the hash parameter from the url after logging in. In the end I decided to swap use of `window.history.replaceState` instead of `router.replace` from next.js because I saw that line in the stack trace of the error, which somehow was only happening in production. This seems to have resolved the issue.
> [SIMPLY-3466] Login Error
